[package]
name = "sts_profile_auth"
version = "0.1.1"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
lazy_static = "1.4"
regex = {version = "1.3", default_features = false}
rusoto_core = {version = "0.42", default_features = false, features=["rustls"]}
rusoto_ec2 = {version = "0.42", default_features = false, features=["rustls"]}
rusoto_ecr = {version = "0.42", default_features = false, features=["rustls"]}
rusoto_sts = {version = "0.42", default_features = false, features=["rustls"]}
rusoto_credential = {version = "0.42"}
